Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/08/2020
Var

   temp : inteiro

Inicio

    escreval("Qual a temperatura que está onde você mora ?")
   leia(temp)

   se temp >= 25 entao
   escreval("Está muito quente!")
   fimse

   se temp < 25 entao
   escreval("Está agradável!")
   fimse

Fimalgoritmo